"""Add photo url columns

Revision ID: 1481e2f177f3
Revises: 57aa7c10520a
Create Date: 2025-10-11 04:17:57.528954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1481e2f177f3'
down_revision: Union[str, Sequence[str], None] = '57aa7c10520a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pakaian', sa.Column('foto_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('foto_profil_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'foto_profil_url')
    op.drop_column('pakaian', 'foto_url')
    # ### end Alembic commands ###
