"""Add soft delete to pakaian table

Revision ID: 57aa7c10520a
Revises: c909df944e93
Create Date: 2025-10-11 03:08:40.278260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57aa7c10520a'
down_revision: Union[str, Sequence[str], None] = 'c909df944e93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pakaian', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pakaian', 'deleted_at')
    # ### end Alembic commands ###
