"""Add password reset token table

Revision ID: 7087877bedf0
Revises: 1481e2f177f3
Create Date: 2025-10-11 05:12:05.768988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7087877bedf0'
down_revision: Union[str, Sequence[str], None] = '1481e2f177f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_reset_tokens', sa.Column('token', sa.String(), nullable=False))
    op.add_column('password_reset_tokens', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False))
    op.create_unique_constraint(None, 'password_reset_tokens', ['token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'password_reset_tokens', type_='unique')
    op.drop_column('password_reset_tokens', 'expires_at')
    op.drop_column('password_reset_tokens', 'token')
    # ### end Alembic commands ###
