"""Refactor: rename all models to English

Revision ID: bebf364b8535
Revises: 7087877bedf0
Create Date: 2025-11-09 18:45:18.229513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bebf364b8535'
down_revision: Union[str, Sequence[str], None] = '7087877bedf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clothing_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('material', sa.String(), nullable=True),
    sa.Column('washing_instructions', sa.String(), nullable=True),
    sa.Column('fades_easily', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clothing_items_id'), 'clothing_items', ['id'], unique=False)
    op.create_index(op.f('ix_clothing_items_name'), 'clothing_items', ['name'], unique=False)
    op.create_table('laundry_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_received', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('estimated_completion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_laundry_sessions_id'), 'laundry_sessions', ['id'], unique=False)
    op.create_table('laundry_session_details',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('clothing_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clothing_item_id'], ['clothing_items.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['laundry_sessions.id'], ),
    sa.PrimaryKeyConstraint('session_id', 'clothing_item_id')
    )
    op.drop_table('detail_sesi_laundry')
    op.drop_index(op.f('ix_sesi_laundry_id'), table_name='sesi_laundry')
    op.drop_table('sesi_laundry')
    op.drop_index(op.f('ix_pakaian_id'), table_name='pakaian')
    op.drop_index(op.f('ix_pakaian_nama_pakaian'), table_name='pakaian')
    op.drop_table('pakaian')
    op.add_column('users', sa.Column('profile_photo_url', sa.String(), nullable=True))
    op.drop_column('users', 'foto_profil_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('foto_profil_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'profile_photo_url')
    op.create_table('pakaian',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('pakaian_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nama_pakaian', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('kategori', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('jenis_pakaian', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('warna', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bahan', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('petunjuk_pencucian', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mudah_luntur', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('pemilik_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('foto_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pemilik_id'], ['users.id'], name='pakaian_pemilik_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='pakaian_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_pakaian_nama_pakaian'), 'pakaian', ['nama_pakaian'], unique=False)
    op.create_index(op.f('ix_pakaian_id'), 'pakaian', ['id'], unique=False)
    op.create_table('sesi_laundry',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('sesi_laundry_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('tanggal_masuk', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('estimasi_selesai', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pemilik_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pemilik_id'], ['users.id'], name='sesi_laundry_pemilik_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='sesi_laundry_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_sesi_laundry_id'), 'sesi_laundry', ['id'], unique=False)
    op.create_table('detail_sesi_laundry',
    sa.Column('sesi_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pakaian_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pakaian_id'], ['pakaian.id'], name=op.f('detail_sesi_laundry_pakaian_id_fkey')),
    sa.ForeignKeyConstraint(['sesi_id'], ['sesi_laundry.id'], name=op.f('detail_sesi_laundry_sesi_id_fkey')),
    sa.PrimaryKeyConstraint('sesi_id', 'pakaian_id', name=op.f('detail_sesi_laundry_pkey'))
    )
    op.drop_table('laundry_session_details')
    op.drop_index(op.f('ix_laundry_sessions_id'), table_name='laundry_sessions')
    op.drop_table('laundry_sessions')
    op.drop_index(op.f('ix_clothing_items_name'), table_name='clothing_items')
    op.drop_index(op.f('ix_clothing_items_id'), table_name='clothing_items')
    op.drop_table('clothing_items')
    # ### end Alembic commands ###
