"""Create pakaian table

Revision ID: c3c3f9b705e4
Revises: 
Create Date: 2025-10-08 23:44:34.998386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3c3f9b705e4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pakaian', sa.Column('nama_pakaian', sa.String(), nullable=False))
    op.add_column('pakaian', sa.Column('kategori', sa.String(), nullable=True))
    op.add_column('pakaian', sa.Column('jenis_pakaian', sa.String(), nullable=True))
    op.add_column('pakaian', sa.Column('warna', sa.String(), nullable=True))
    op.add_column('pakaian', sa.Column('bahan', sa.String(), nullable=True))
    op.add_column('pakaian', sa.Column('petunjuk_pencucian', sa.String(), nullable=True))
    op.add_column('pakaian', sa.Column('mudah_luntur', sa.Boolean(), nullable=True))
    op.add_column('pakaian', sa.Column('pemilik_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_pakaian_id'), 'pakaian', ['id'], unique=False)
    op.create_index(op.f('ix_pakaian_nama_pakaian'), 'pakaian', ['nama_pakaian'], unique=False)
    op.create_foreign_key(None, 'pakaian', 'users', ['pemilik_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pakaian', type_='foreignkey')
    op.drop_index(op.f('ix_pakaian_nama_pakaian'), table_name='pakaian')
    op.drop_index(op.f('ix_pakaian_id'), table_name='pakaian')
    op.drop_column('pakaian', 'pemilik_id')
    op.drop_column('pakaian', 'mudah_luntur')
    op.drop_column('pakaian', 'petunjuk_pencucian')
    op.drop_column('pakaian', 'bahan')
    op.drop_column('pakaian', 'warna')
    op.drop_column('pakaian', 'jenis_pakaian')
    op.drop_column('pakaian', 'kategori')
    op.drop_column('pakaian', 'nama_pakaian')
    # ### end Alembic commands ###
