"""Create laundry session tables

Revision ID: c909df944e93
Revises: c3c3f9b705e4
Create Date: 2025-10-09 00:27:33.648326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c909df944e93'
down_revision: Union[str, Sequence[str], None] = 'c3c3f9b705e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detail_sesi_laundry', sa.Column('sesi_id', sa.Integer(), nullable=False))
    op.add_column('detail_sesi_laundry', sa.Column('pakaian_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'detail_sesi_laundry', 'pakaian', ['pakaian_id'], ['id'])
    op.create_foreign_key(None, 'detail_sesi_laundry', 'sesi_laundry', ['sesi_id'], ['id'])
    op.add_column('sesi_laundry', sa.Column('tanggal_masuk', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('sesi_laundry', sa.Column('estimasi_selesai', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sesi_laundry', sa.Column('status', sa.String(), nullable=True))
    op.add_column('sesi_laundry', sa.Column('pemilik_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_sesi_laundry_id'), 'sesi_laundry', ['id'], unique=False)
    op.create_foreign_key(None, 'sesi_laundry', 'users', ['pemilik_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sesi_laundry', type_='foreignkey')
    op.drop_index(op.f('ix_sesi_laundry_id'), table_name='sesi_laundry')
    op.drop_column('sesi_laundry', 'pemilik_id')
    op.drop_column('sesi_laundry', 'status')
    op.drop_column('sesi_laundry', 'estimasi_selesai')
    op.drop_column('sesi_laundry', 'tanggal_masuk')
    op.drop_constraint(None, 'detail_sesi_laundry', type_='foreignkey')
    op.drop_constraint(None, 'detail_sesi_laundry', type_='foreignkey')
    op.drop_column('detail_sesi_laundry', 'pakaian_id')
    op.drop_column('detail_sesi_laundry', 'sesi_id')
    # ### end Alembic commands ###
